<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @author Geoffray Warnants
 * @version 0.2b
 */

//
// Database "gameloftshop"
//

// gameloftshop.products
$products = array(
  array('id'=>953,'name'=>'Asphalt 5 HD+'),
  array('id'=>1036,'name'=>'Gameloft HD Games'),
  array('id'=>1043,'name'=>'Let\'s Golf HD+'),
  array('id'=>1044,'name'=>'Modern Combat: Sandstorm HD+'),
  array('id'=>1045,'name'=>'N.O.V.A. HD+'),
  array('id'=>1048,'name'=>'UNO HD+'),
  array('id'=>1049,'name'=>'Gangstar West Coast Hustle HD+'),
  array('id'=>1050,'name'=>'Assassin\'s Creed HD+'),
  array('id'=>1051,'name'=>'Dungeon Hunter HD+'),
  array('id'=>1052,'name'=>'Hero of Sparta HD+'),
  array('id'=>1053,'name'=>'Hawx HD+'),
  array('id'=>1055,'name'=>'2010 Real Soccer HD+'),
  array('id'=>1068,'name'=>'Let\'s Golf 2 HD+'),
  array('id'=>1069,'name'=>'GT Racing: Motor Academy HD+'),
  array('id'=>1081,'name'=>'Avatar HD+'),
  array('id'=>1096,'name'=>'Splinter Cell Conviction HD+'),
  array('id'=>1102,'name'=>'Asphalt 6: Adrenaline HD+'),
  array('id'=>1109,'name'=>'Fishing Kings HD+'),
  array('id'=>1120,'name'=>'Guitar Rock Tour 2 HD+'),
  array('id'=>1122,'name'=>'Real Golf 2011 HD+'),
  array('id'=>1128,'name'=>'Brothers In Arms 2 : Global Front HD+'),
  array('id'=>1141,'name'=>'Shrek Karting HD+'),
  array('id'=>1142,'name'=>'Spider-Man: Total Mayhem HD+'),
  array('id'=>1143,'name'=>'Oregon Trail HD+'),
  array('id'=>1144,'name'=>'2011 Real Football HD+'),
  array('id'=>1145,'name'=>'The Settlers HD+'),
  array('id'=>1147,'name'=>'Modern Combat 2: Black Pegasus HD+'),
  array('id'=>1148,'name'=>'Gangstar: Miami Vindication HD+'),
  array('id'=>1164,'name'=>'2011 Real Soccer HD+'),
  array('id'=>1187,'name'=>'Sacred Odyssey: The Rise of Ayden HD+'),
  array('id'=>1188,'name'=>'Star Front: Collision HD+'),
  array('id'=>1189,'name'=>'Rainbow 6: Shadow Vanguard HD+'),
  array('id'=>1195,'name'=>'Fast 5 HD+'),
  array('id'=>1196,'name'=>'Dungeon Hunter 2 HD+'),
  array('id'=>1197,'name'=>'N.O.V.A. 2 HD+'),
  array('id'=>1198,'name'=>'Eternal Legacy HD+'),
  array('id'=>1202,'name'=>'Dungeon Hunter 3 Free+'),
  array('id'=>1213,'name'=>'GT Racing: Motor Academy Free+'),
  array('id'=>1218,'name'=>'Shadow Guardian HD+'),
  array('id'=>1224,'name'=>'N.O.V.A. 3 Paymium HD+'),
  array('id'=>1226,'name'=>'Six Guns Free+'),
  array('id'=>1235,'name'=>'Backstab HD+'),
  array('id'=>1242,'name'=>'Fantasy Town Free+'),
  array('id'=>1245,'name'=>'9mm Paymium HD+'),
  array('id'=>1256,'name'=>'Order & Chaos Paymium HD+'),
  array('id'=>1266,'name'=>'The Oregon Trail: American Settler Free+'),
  array('id'=>1267,'name'=>'Cosmic Colony  Free+'),
  array('id'=>1273,'name'=>'Gangstar Rio: City of Saints Paymium HD+'),
  array('id'=>1275,'name'=>'Modern Combat 3 Paymium HD+'),
  array('id'=>1279,'name'=>'Fashion Icon Free+'),
  array('id'=>1284,'name'=>'Spider-Man: Total Mayhem 3D HD+'),
  array('id'=>1285,'name'=>'Assassin\'s Creed 3D HD+'),
  array('id'=>1286,'name'=>'Avatar 3D HD+'),
  array('id'=>1288,'name'=>'Fishing Kings 3D HD+'),
  array('id'=>1289,'name'=>'Shrek Karting 3D HD+'),
  array('id'=>1290,'name'=>'GT Racing: Motor Academy 3D HD+'),
  array('id'=>1291,'name'=>'Modern Combat 2: Black Pegasus 3D HD+'),
  array('id'=>1292,'name'=>'Dungeon Hunter 2 3D HD+'),
  array('id'=>1293,'name'=>'N.O.V.A. 2 3D HD+'),
  array('id'=>1294,'name'=>'Star Battalion 3D HD+'),
  array('id'=>1295,'name'=>'Backstab 3D HD+'),
  array('id'=>1296,'name'=>'Shadow Guardian 3D HD+'),
  array('id'=>1297,'name'=>'Eternal Legacy 3D HD+'),
  array('id'=>1298,'name'=>'Wild Blood Paymium HD+ Android'),
  array('id'=>1299,'name'=>'Asphalt 6: Adrenaline 3D HD+'),
  array('id'=>1300,'name'=>'Let\'s Golf 2 3D HD+'),
  array('id'=>1301,'name'=>'N.O.V.A. 3D HD+'),
  array('id'=>1302,'name'=>'Block Breaker 3 Paymium HD+'),
  array('id'=>1303,'name'=>'Let\'s Golf 3 Free+'),
  array('id'=>1304,'name'=>'Green Farm Mobile HD+ Free+'),
  array('id'=>1305,'name'=>'Asphalt 7: Heat Paymium HD+'),
  array('id'=>1308,'name'=>'Gameloft Live! 3D'),
  array('id'=>1309,'name'=>'2011 Real Soccer 3D HD+'),
  array('id'=>1313,'name'=>'Brothers In Arms 2 : Global Front Free+'),
  array('id'=>1315,'name'=>'NFL Pro 2012 Free+'),
  array('id'=>1328,'name'=>'Men In Black 3 Free+'),
  array('id'=>1351,'name'=>'Order & Chaos Paymium 3D HD+'),
  array('id'=>1358,'name'=>'The adventures of TINTIN: The Secret of the Unicorn HD+'),
  array('id'=>1359,'name'=>'Zombiewood Free+'),
  array('id'=>1367,'name'=>'Littlest Pet Shop Free+'),
  array('id'=>1370,'name'=>'My little Pony Free+'),
  array('id'=>1371,'name'=>'Kingdoms & Lords Free+'),
  array('id'=>1373,'name'=>'Shark Dash Paymium HD+'),
  array('id'=>1374,'name'=>'Heroes of Order and Chaos Free+'),
  array('id'=>1376,'name'=>'World At Arms Free+'),
  array('id'=>1379,'name'=>'Block Breaker 3 Free+'),
  array('id'=>1387,'name'=>'Splinter Cell Conviction 3D HD+'),
  array('id'=>1388,'name'=>'Asphalt 6: Adrenaline Paymium HD+'),
  array('id'=>1390,'name'=>'Ice Age Village Free+'),
  array('id'=>1395,'name'=>'Oregon Trail Paymium HD+'),
  array('id'=>1399,'name'=>'2012 Real Soccer Free+'),
  array('id'=>1402,'name'=>'Uno Free HD+ (ad supported)'),
  array('id'=>1414,'name'=>'Monster Life Free+'),
  array('id'=>1430,'name'=>'Gang Domination HD+ GREE'),
  array('id'=>1436,'name'=>'The Amazing Spiderman Paymium HD+'),
  array('id'=>1481,'name'=>'Where is Wally Now HD+'),
  array('id'=>1494,'name'=>'The Dark Knight Rises Paymium HD+'),
  array('id'=>1507,'name'=>'Wonder Zoo Free+'),
  array('id'=>1511,'name'=>'2013 Real Soccer Free+'),
  array('id'=>1514,'name'=>'NFL Pro 2013 Free+'),
  array('id'=>1526,'name'=>'Shark Dash FREE'),
  array('id'=>1547,'name'=>'Playmobil Pirates Free+'),
  array('id'=>1563,'name'=>'AMA Babel Rising 3D'),
  array('id'=>1571,'name'=>'GT Racing: Motor Academy Hyundai Free+'),
  array('id'=>1597,'name'=>'Modern Combat 4: Zero Hour Paymium HD+'),
  array('id'=>1599,'name'=>'Asphalt 7: Heat HD+')
);
